# Generated by Django 4.2 on 2023-06-12 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cinema', '0002_alter_cinemasession_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieseason',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='ticket_price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
