# Generated by Django 4.2 on 2023-06-15 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cinema', '0003_remove_movieseason_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemasession',
            options={'ordering': ['movie_show_starts_date', 'movie_show_starts_time']},
        ),
        migrations.AlterUniqueTogether(
            name='cinemasession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='movieseason',
            name='movie_show_time_ends',
        ),
        migrations.RemoveField(
            model_name='movieseason',
            name='movie_show_time_starts',
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_ends_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_ends_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_starts_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_starts_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cinemasession',
            unique_together={('cinema_hall', 'movie_show_starts_date', 'movie_show_starts_time')},
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_ends',
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_starts',
        ),
    ]
