# Generated by Django 4.2 on 2023-06-15 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cinema', '0004_alter_cinemasession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemasession',
            options={'ordering': ['movie_show_starts']},
        ),
        migrations.AlterUniqueTogether(
            name='cinemasession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemasession',
            name='movie_show_starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cinemasession',
            unique_together={('cinema_hall', 'movie_show_starts')},
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_ends_date',
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_ends_time',
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_starts_date',
        ),
        migrations.RemoveField(
            model_name='cinemasession',
            name='movie_show_starts_time',
        ),
    ]
