# Generated by Django 4.2 on 2023-06-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cinema', '0005_alter_cinemasession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemasession',
            name='title',
        ),
    ]
