# Generated by Django 4.2 on 2023-06-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cinema', '0007_movieseason_film_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieseason',
            old_name='img_url',
            new_name='img',
        ),
    ]
